POST http://localhost:3333/api/users
Content-Type: application/json

{
    "name": "jek",
    "email": "jek@gmail.com",
    "password": "jek@gmail.com"
}

###
POST http://localhost:3333/api/users/auth
Content-Type: application/json

{
    "email": "jek@gmail.com",
    "password": "jek@gmail.com"
}

###
POST http://localhost:3333/api/users/logout
Content-Type: application/json

###
GET http://localhost:3333/api/users/profile

###
PUT http://localhost:3333/api/users/profile
Content-Type: application/json

{
    "email": "jek@gmail.com"
    }

###